productly/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('admin/', admin.site.urls),
    path('productos/',include('productos.urls')),
]

productos/urls.py
from django.urls import path
from . import views
app_name = 'productos'
urlpatterns = [
    path('', views.index, name='index' ),
    path('formulario', views.formulario, name='formulario' ),
    path(
        '<int:producto_id>',
        views.detalle,
        name='detalle'
    ),
]

productos/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=255)
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nombre = models.CharField(max_length=255)
    stock = models.IntegerField()
    puntaje = models.FloatField()
    #CASCADE: ELIMANAR EL PRODUCTO
    #PROTECT: LANZA UN ERROR
    #RESTRIC: SOLO ELIMINA SI NO EXISTEN PRODCUTOS
    #SET_NULL: ACTUALIZA A VALOR NULO
    #SET_DEFAULT:  ACTUALIZA AL VALOR POR DEFECTO QUE SE HAYA INGRESADO EN DEFAULT_VALUE
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    
    creado_en = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.nombre

productos/forms.py
from django.forms import ModelForm
from . import models

class ProductoForm(ModelForm):
    class Meta:
        model = models.Producto
        fields = ['nombre', 'stock', 'puntaje', 'categoria']
        
#-------------------------------------------------------------

productly/views.py
from django.shortcuts import render

def inicio(request):
    return render(request, 'inicio.html')

productos/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.shortcuts import render, get_object_or_404

from .forms import ProductoForm
from .models import Producto
# Create your views here.

def index(request):
    productos = Producto.objects.all()
    
    return render(
        request,
        'index.html',
        context= {'productos': productos}
    )
def detalle(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    producto = Producto.objects.get(id=producto_id)
    
    return render(
        request,
        'detalle.html',
        context={'producto': producto})
    
def formulario(request):
    if request.method=='POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/productos')
    else:
        form = ProductoForm()
    return render(
        request,
        'producto_form.html',
        {'form': form}
    )

productos/templates/detalle.html
{% extends 'base.html' %}

{% block title %}Detalle{% endblock %}

{% block content %}
    <h1>Detalle</h1>
    <p>Este es el detalle del producto</p>
<div>
    <h6>{{producto.nombre}}</h6>
    <p>{{producto.categoria}}</p>
    <p>{{producto.stock}}</p>
    <p>{{producto.puntaje}}</p>
    <p>{{producto.creado_en}}</p>
</div>
{% endblock %}
<!-- Your content goes here -->

productos/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Productos</h1>
<a href="{% url 'productos:formulario' %}">Crear Producto</a> <br/>

<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Stock</th>
            <th>Puntaje</th>
            <th>Categoria</th>
        </tr>
    </thead>
    <tbody>
        {% for producto in productos %}
        <tr>
            <td>{{ producto.nombre }}</td>
            <td>{{ producto.stock }}</td>
            <td>{{ producto.puntaje }}</td>
            <td>{{ producto.categoria }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

productos/templates/producto_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Formulario de productos</h1>
<form
    novalidate
    action="{%url 'productos:formulario' %}"
    method='post'>
    {%csrf_token%}
    {{ form }}
    <input type="submit" value="Enviar"/>
</form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>productly</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Hello World!</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url "inicio" %}">Inicio</a>
              <a class="nav-link" href="{% url "productos:index" %}">Productos</a>
              <a class="nav-link" href="#">Pricing</a>
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </div>
          </div>
        </div>
      </nav>
    <div class="container">
    
    {% block content %}

    {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/django/forms/label.html
{% if use_tag %}<{{ tag }}{% include 'django/forms/attrs.html' %}class="form-label">{{ label }}</{{ tag }}>{% else %}{{ label }}{% endif %}

templates/django/forms/windges/input.html
<input
class = "form-control"
type="{{ widget.type }}" 
name="{{ widget.name }}"
{% if widget.value != None %} 
value="{{ widget.value|stringformat:'s' }}"
{% endif %}
{% include "django/forms/widgets/attrs.html" %}>

templates/form_snippet.html
{%for field in form%}
<div class="mb-3">
    {{field.label_tag}} {{field}}
    <div class="invalid-feedback">
    {%for error in field.errors%}
        {{error}}
    {%endfor%}
    </div>
</div>
{%endfor%}

templates/inicio.html
{% extends 'base.html'%}
{% block content %}
    <div class="home-page">
        <h1 style="color: blue;">Welcome to Productly!</h1>
        <p>Discover amazing products and services.</p>
    </div>
{% endblock %}